### ISSUE TITLE
Merging Strategy

### ISSUE THREAD

**Issue by billiemj** [billiemj/webapp#4]
We need to make some decisions on our merging strategy. Shall we use Fork or local? Do we want to have certain naming conventions for our branch names? 

I did set the repository so that two people need to review the pull request before it can be removed. For more information on configuration option see article [Configuring protected branches](https://help.github.com/en/articles/configuring-protected-branches)

**Comment by sciencenerd** [comment]
I think I prefer the Fork idea, but I could be sold on either. Once a decision is made, I would like to see a walkthrough of how we would keep the Fork (or local branch) updated when changes are made locally. We should also add these TBD commands to our Github cheatsheet.

**Comment by billiemj** [comment]
Closing out. Moved issue to JiRA
